# Site settings
title: RealCodez
email: realcodez@clabs.org
description: > # this means to ignore newlines until "baseurl:"
  Where real world development meets real world failure and frustration for your entertainucation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://realcodez.com" # the base hostname & protocol for your site
twitter_username: realcodez
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
